type: DeconvEncoder
args:
  layer: GatedDeconvLayer
  nnlin: SiLU
  channels: [8,16,32,64]
  dilation: [1,1,1,1]
  stride: [8,4,4,2]
  kernel_size: [17,15,13,11]
  norm: batch
  # target_dist: Normal
  final_conv: 1
  out_nnlin: Softplus
  bias: True 