type: DeconvEncoder
args:
  layer: DeconvLayer
  nnlin: ELU
  channels: [8,16,32,64]
  dilation: [1,1,1,1,1]
  stride: [4,4,2,1]
  kernel_size: [13,11,9,5]
  norm: batch
  final_conv: 0
  bias: True 
